[project]
name = "se333finalproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=2.13.0.2",
    "httpx>=0.28.1",
    "mcp[cli]>=1.21.0",
]
